dist: xenial
language: node
node_js: 
  - node
stages:
  - name: client

jobs:
  include:
    - name: Website Unit Testing
      stage: client
      script:
        - sudo apt-get install libpixman-1-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev libgif-dev  libjpeg-dev
        - cd website
        - yarn install
        - yarn test
    - name: Mobile Testing
      stage: client
      script:
        - cd mobile
        - yarn install
        - yarn test
    # - name: API Unit Testing
    #   stage: api
    #   script: echo "api testing here"
## Tests that are not unit testing can be added
## to the same stage as a new job like so:
    # - name: Website Acceptance Testing
    #   stage: website
    #   script: do whatever acceptance testing is